Practice1
Vasily9/polytech-frontend-2017 pull request #1
Opened 2017-10-06 10:28 UTC by Vasily9

2017-10-06 14:27 UTC, Chudesnov requested changes

2017-10-06 14:27 UTC, Chudesnov commented on src/nav.js
> +<div onClick={this.clickMe.bind(this)}>
bind будет выполняться при каждом рендере компонента, лучше делать в конструкторе, он вызовется только один раз.

2017-10-12 18:46 UTC, Vasily9 commented
Добавлен prettier, bind перенесен в конструктор

2017-10-19 22:10 UTC, Chudesnov approved these changes

2018-12-10 14:05 UTC, closed without merging