Practice2
Vasily9/polytech-frontend-2017 pull request #2
Opened 2017-10-06 10:31 UTC by Vasily9

2017-10-11 17:05 UTC, Chudesnov requested changes

2017-10-11 17:05 UTC, Chudesnov commented on vue/app.js
> +new Vue({
Надо добавить и сюда prettier

2017-10-12 19:02 UTC, Vasily9 commented
Добавлен prettier. Папка vue копирована в src для работы prettier

2017-10-13 08:54 UTC, Chudesnov requested changes

2017-10-13 08:54 UTC, Chudesnov commented on package.json
> +    /*husky выполнит эту команду, когда вы попытаетесь сделать git commit */
комментарии в JSON невалидны, их надо было вырезать при копировании

2017-10-13 08:54 UTC, Chudesnov commented on src/vue/app.js
> +new Vue({
Код по-прежнему не отформатирован. Исправь его вручную через `prettier --write`

2017-10-13 08:54 UTC, Chudesnov commented on src/vue/index.html
> +<!DOCTYPE html>
HTML тоже должен быть отформатирован консистентно: у вложенных элементов должен быть увеличен отступ, пробелов между названиями и значениями атрибутов быть не должно.

2017-10-19 22:10 UTC, Chudesnov approved these changes

2018-12-10 14:05 UTC, closed without merging